### PR TITLE
feat(chars): support unicode and octal char literals

### PR DESCRIPTION
**Pull request by Samy-33**
image

### CODE REVIEW

File: compiler+runtime/include/cpp/jank/read/parse.hpp [hunk 1]
```diff
@@ -12,33 +14,75 @@ namespace jank::runtime
...
+      return none;
+    }
+    catch(std::invalid_argument const)
+    {
+      return none;
+    }
+    catch(std::out_of_range const)
+    {
+      return none;
+    }
```
Comment (jeaye) [inline compiler+runtime/include/cpp/jank/read/parse.hpp:56]: Just one `catch(std::exception const &)` will do. Always catch exceptions by reference.

File: compiler+runtime/include/cpp/jank/read/parse.hpp [hunk 2]
```diff
@@ -12,33 +14,75 @@ namespace jank::runtime
...
+        std::stol(native_persistent_string{ char_literal.data() + 2, char_literal.size() - 2 },
+                  &chars_processed,
+                  base));
+
+      /* Some characters that weren't processed at all.
+       * An example would be when trying to parse `12a` in octal base,
+       * `stol` will only parse `12` and will ignore `a`, returning `2`
+       * in `chars_processed`.
+       * We return none in that case, to represent to the downstream callers
+       * the enability to parse the char literal.
```
Comment (jeaye) [inline compiler+runtime/include/cpp/jank/read/parse.hpp:33]: Please update this comment to convey that we're checking for this case, rather than this being the case. When I read "Some characters that weren't processed at all", I think there's a problem. Perhaps: "We check for characters that were unable to be processed."

Also: `s/enability/inability/`

Overall, I like this helpful comment, though. :+1:

File: compiler+runtime/src/cpp/jank/read/parse.cpp [hunk 3]
```diff
@@ -348,6 +348,41 @@ namespace jank::read::parse
 
     if(character.is_none())
     {
+      /* Unicode */
```
Comment (jeaye) [inline compiler+runtime/src/cpp/jank/read/parse.cpp:351]: This is hexadecimal Unicode. The other branch is octal Unicode.

File: compiler+runtime/src/cpp/jank/read/parse.cpp [hunk 4]
```diff
@@ -348,6 +348,41 @@ namespace jank::read::parse
...
+      if(sv[0] == '\\' && sv[1] == 'u')
+      {
+        /* Should always be of length 6 eg. \uaBc5 */
```
Comment (jeaye) [inline compiler+runtime/src/cpp/jank/read/parse.cpp:354]: This is how Clojure handles it, but I don't think we should have this limitation. For example, `\u1f920` is needed for 🤠. Same goes for octal. We should read however much is there, I think, as long as it's one codepoint.

File: compiler+runtime/include/cpp/jank/read/parse.hpp [hunk 5]
```diff
@@ -12,33 +14,75 @@ namespace jank::runtime
...
+       *
+       * Refer: https://en.cppreference.com/w/cpp/string/basic_string/stol
+       */
+      if(chars_processed != char_literal.size() - 2)
+      {
+        return none;
+      }
+
+      std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> converter;
```
Comment (jeaye) [inline compiler+runtime/include/cpp/jank/read/parse.hpp:42]: The `converter` has a member fn on it to check how many codepoints were consumed. We could check that this is `1` and fail otherwise. Also, we may be getting into an area here where `result` is more useful than `option`.

File: compiler+runtime/include/cpp/jank/read/parse.hpp [hunk 6]
```diff
@@ -12,33 +14,75 @@ namespace jank::runtime
 /* TODO: Rename file to processor. */
 namespace jank::read::parse
 {
-  static option<char> get_char_from_literal(native_persistent_string const &sv)
+  static option<native_persistent_string>
+  parse_character_in_base(native_persistent_string_view const &char_literal, int const base)
```
Comment (jeaye) [inline compiler+runtime/include/cpp/jank/read/parse.hpp:18]: I think that it's odd to keep the `\o` or `\u` prefix on this when parsing. We should strip it out using `substr` before calling.

File: compiler+runtime/include/cpp/jank/read/parse.hpp (hunk 1 above)
Comment (Samy-33) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:56]: `catch(std::exception const &)` will catch all exceptions. Even the ones thrown not because of wrong syntax.

Why is that better in that case?

File: compiler+runtime/include/cpp/jank/read/parse.hpp (hunk 5 above)
Comment (Samy-33) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:42]: Is it because we also want to return the cause of the error?

If so, what's the purpose of returning cause of the error? Is it to show a better error message?

Comment (jeaye) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:42]: Yes and yes!

File: compiler+runtime/include/cpp/jank/read/parse.hpp (hunk 6 above)
Comment (jeaye) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:18]: Let's be not use a string_view here, though. I'm thinking of removing them from the supported jank types entirely, since they're altogether too difficult to use. For example, if we kept the string_view as the arg and we changed our call sites to use `substr`, we'd have undefined behavior since `substr` returns a temporary string, which we then borrow with the string_view and that doesn't keep it alive. Much better to just use a ref to const persistent string.

File: compiler+runtime/include/cpp/jank/read/parse.hpp (hunk 1 above)
Comment (jeaye) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:56]: We ant all exceptions caught here, since we're encoding error handling in the return type. Having an `option` or a `result` as a return type AND having to deal with exceptions is the worst of both worlds, in terms of API design.

File: compiler+runtime/test/cpp/jank/read/parse.cpp [hunk 7]
```diff
@@ -244,10 +246,10 @@ namespace jank::read::parse
 
         SUBCASE("Invalid length")
         {
-          lex::processor lp{ R"(\o1 \o23 \o4567 \o0123454)" };
+          lex::processor lp{ R"(\o12345677 \o23007673323)" };
```
Comment (jeaye) [inline compiler+runtime/test/cpp/jank/read/parse.cpp:249]: What makes these invalid length?

File: compiler+runtime/include/cpp/jank/read/parse.hpp [hunk 8]
```diff
@@ -12,33 +14,74 @@ namespace jank::runtime
 /* TODO: Rename file to processor. */
 namespace jank::read::parse
 {
-  static option<char> get_char_from_literal(native_persistent_string const &sv)
+  static result<option<native_persistent_string>, native_persistent_string>
```
Comment (jeaye) [inline compiler+runtime/include/cpp/jank/read/parse.hpp:17]: Both of these fns should be defined in the `.cpp` file, not the `.hpp` file. They're not templates. By having them be `static`, we're actually putting a separate copy of this fn into every single translation unit. We'll have over 80 copies of this fn in the jank program this way; they'll all be identical.

File: compiler+runtime/test/cpp/jank/read/parse.cpp (hunk 7 above)
Comment (jeaye) [reply compiler+runtime/test/cpp/jank/read/parse.cpp:275]: Fair enough.

File: compiler+runtime/include/cpp/jank/read/parse.hpp (hunk 8 above)
Comment (jeaye) [reply compiler+runtime/include/cpp/jank/read/parse.hpp:17]: Based on your questions, this needs to be explained in a few parts.

## Translation units
A translation unit (TU), in C++, is everything which compiles down to an object file (`.o`). Generally, this ties 1:1 with `.cpp` files. Each TU is compiled separately, based on the code within the `.cpp` file and all the headers included. If multiple TUs include the same header, they do all the same duplicate work to parse it.

## Linkage
Within a TU, symbols can have different types of linkage. This is what makes the symbols within the TU available to other TUs when they're linked together into a program. By default, symbols have external linkage, meaning the symbols can be accessed by other TUs when everything is linked. Furthermore, with external linkage, there may be only one definition per symbol. This is the one definition rule (ODR).

However, putting `static` on a free fn or var gives it internal linkage, which allows multiple definitions with the same name, since they don't compete in the global symbol space. Many TUs may a definition of a symbol, even differing definitions, as long as that symbol has internal linkage.

## Inline
There is another way to get around the ODR, for functions, which is to use `inline`. A function with external linkage can be marked `inline` and it will still be allowed to have multiple definitions, though still only one per TU. This allows multiple TUs to include a header which defines an inline fn without linker errors.

Function templates are implicitly inline and are generally defined in headers to be included into many TUs.

## Static
Note that the `static` keyword, in C++, has a few different meanings. Only one of them implies internal linkage. All of the meanings are noted here: https://en.cppreference.com/w/cpp/keyword/static

## Wrap
So, by having your function defined in a header and marked `static`, every TU which includes it will get its own copy, with internal linkage. This is a recipe for code bloat in the resulting binary. We have two options:

1. Mark the function `inline`, rather than `static`
2. Define the fn in a single TU and make sure it has external linkage (no `static`) and then just forward declare it in a header which is included by other TUs

Which one to choose? Well, we don't want the first one, since defining too many inline fns in headers slows down compilation. Remember, every TU which includes that header needs to process it. This takes time. In this case, it's in a common header, too. So our choice is number 2.

How does that work? Well, every TU which wants to call this fn, but which doesn't define it, will reference the symbol, but it will remain unresolved in that TU's generated `.o` file. This is ok. Once all of the `.o` files are linked together into our `jank` binary, all symbols are resolved. As long as we link in the TU which has that fn, and the fn has external linkage, we're golden. If not, we'll get linker errors.

You'll see this is the pattern that we use already in jank. For example:

* Declaration: https://github.com/jank-lang/jank/blob/main/compiler%2Bruntime/include/cpp/jank/runtime/core/seq.hpp#L172
* Definition: https://github.com/jank-lang/jank/blob/main/compiler%2Bruntime/src/cpp/jank/runtime/core/seq.cpp#L14

File: compiler+runtime/src/cpp/jank/read/parse.cpp [hunk 9]
```diff
@@ -15,6 +15,81 @@ namespace jank::read::parse
 {
   using namespace jank::runtime;
 
+  result<option<native_persistent_string>, native_persistent_string>
```
Comment (jeaye) [inline compiler+runtime/src/cpp/jank/read/parse.cpp:18]: `result<option<T>, E>` implies that `ok(none)` is expected, but we're never returning that. Why do we have the `option<T>` in there at all?

File: compiler+runtime/src/cpp/jank/read/parse.cpp [hunk 10]
```diff
@@ -15,6 +15,81 @@ namespace jank::read::parse
...
+       * Refer: https://en.cppreference.com/w/cpp/string/basic_string/stol
+       */
+      if(chars_processed != char_literal.size())
+      {
+        return err("Invalid unicode digit");
+      }
+
+      std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> converter;
+
+      auto const converted(native_persistent_string{ converter.to_bytes(codepoint) });
```
Comment (jeaye) [inline compiler+runtime/src/cpp/jank/read/parse.cpp:44]: Here we're using `auto` and the `type`. If we need to specify the type, just specify the type.

```cpp
native_persistent_string const converted{ converter.to_bytes(codepoint) };
```

**Comment by jeaye** [comment]
Great work!
